import type { VideoAsciiSettings } from './colorVideoAscii';

const TERMINAL_ASCII_RAMP = '@#W$9876543210?!abc;:+=-,._ ';

function serializeSetting(value: number): string {
  return Number(value.toFixed(4)).toString();
}

function buildTerminalAsciiPythonProgram(settings: VideoAsciiSettings): string {
  const configJson = JSON.stringify({
    brightness: Number(serializeSetting(settings.brightness)),
    colorBoost: Number(serializeSetting(settings.colorBoost)),
    contrast: Number(serializeSetting(settings.contrast)),
    density: Number(serializeSetting(settings.density)),
    invert: settings.invert,
  });

  return [
    'import json',
    'import os',
    'import shutil',
    'import subprocess',
    'import sys',
    'import time',
    '',
    `ASCII_RAMP = ${JSON.stringify(TERMINAL_ASCII_RAMP)}`,
    `CONFIG = json.loads(${JSON.stringify(configJson)})`,
    '',
    'def clamp(value, minimum, maximum):',
    '    return min(maximum, max(minimum, value))',
    '',
    'def parse_fraction(value):',
    '    if value is None or value == "":',
    '        return 24.0',
    '    if isinstance(value, (int, float)):',
    '        return float(value)',
    '    text = str(value)',
    '    if "/" in text:',
    '        numerator, denominator = text.split("/", 1)',
    '        try:',
    '            denominator_value = float(denominator)',
    '            if denominator_value == 0:',
    '                return 24.0',
    '            return float(numerator) / denominator_value',
    '        except ValueError:',
    '            return 24.0',
    '    try:',
    '        return float(text)',
    '    except ValueError:',
    '        return 24.0',
    '',
    'def parse_bool(value, default=False):',
    '    if value is None:',
    '        return default',
    '    return str(value).strip().lower() in {"1", "true", "yes", "on"}',
    '',
    'def require_binary(name):',
    '    if shutil.which(name) is None:',
    '        raise RuntimeError(f"{name} is required to run this export.")',
    '',
    'def probe_video(path):',
    '    command = [',
    '        "ffprobe",',
    '        "-v", "error",',
    '        "-print_format", "json",',
    '        "-show_streams",',
    '        "-select_streams", "v:0",',
    '        path,',
    '    ]',
    '    result = subprocess.run(command, capture_output=True, text=True, check=True)',
    '    payload = json.loads(result.stdout or "{}")',
    '    stream = (payload.get("streams") or [{}])[0]',
    '    width = int(stream.get("width") or 0)',
    '    height = int(stream.get("height") or 0)',
    '    fps = clamp(parse_fraction(stream.get("avg_frame_rate") or stream.get("r_frame_rate")), 6.0, 30.0)',
    '    if width <= 0 or height <= 0:',
    '        raise RuntimeError("Could not read the video dimensions with ffprobe.")',
    '    return {"width": width, "height": height, "fps": fps}',
    '',
    'def remap_pixel(red, green, blue):',
    '    contrast = CONFIG["contrast"]',
    '    brightness = CONFIG["brightness"]',
    '    color_boost = CONFIG["colorBoost"]',
    '    red_normalized = red / 255.0',
    '    green_normalized = green / 255.0',
    '    blue_normalized = blue / 255.0',
    '    average = (red_normalized + green_normalized + blue_normalized) / 3.0',
    '    boosted_red = average + (red_normalized - average) * color_boost',
    '    boosted_green = average + (green_normalized - average) * color_boost',
    '    boosted_blue = average + (blue_normalized - average) * color_boost',
    '    adjusted_red = clamp((boosted_red - 0.5) * contrast + 0.5 + brightness, 0.0, 1.0)',
    '    adjusted_green = clamp((boosted_green - 0.5) * contrast + 0.5 + brightness, 0.0, 1.0)',
    '    adjusted_blue = clamp((boosted_blue - 0.5) * contrast + 0.5 + brightness, 0.0, 1.0)',
    '    luminance = clamp(adjusted_red * 0.2126 + adjusted_green * 0.7152 + adjusted_blue * 0.0722, 0.0, 1.0)',
    '    if CONFIG["invert"]:',
    '        luminance = 1.0 - luminance',
    '    return (',
    '        int(round(adjusted_red * 255)),',
    '        int(round(adjusted_green * 255)),',
    '        int(round(adjusted_blue * 255)),',
    '        luminance,',
    '    )',
    '',
    'def pick_char(luminance):',
    '    index = int(round(clamp(luminance, 0.0, 1.0) * (len(ASCII_RAMP) - 1)))',
    '    return ASCII_RAMP[index]',
    '',
    'def resolve_geometry(meta):',
    '    terminal_size = shutil.get_terminal_size((100, 36))',
    '    terminal_columns = max(40, terminal_size.columns - 1)',
    '    density = clamp(CONFIG["density"], 0.72, 1.55)',
    '    density_scale = clamp(0.62 + density * 0.28, 0.68, 1.0)',
    '    columns = max(32, min(terminal_columns, int(terminal_columns * density_scale)))',
    '    requested_columns = os.environ.get("ASCII_VIDEO_COLS", "").strip()',
    '    if requested_columns:',
    '        try:',
    '            columns = max(32, min(terminal_columns, int(float(requested_columns))))',
    '        except ValueError:',
    '            pass',
    '    requested_fps = os.environ.get("ASCII_VIDEO_FPS", "").strip()',
    '    fps = meta["fps"]',
    '    if requested_fps:',
    '        try:',
    '            fps = clamp(float(requested_fps), 6.0, 30.0)',
    '        except ValueError:',
    '            pass',
    '    char_aspect = 0.55',
    '    max_rows = max(16, terminal_size.lines - 2)',
    '    rows = max(12, min(max_rows, int(columns * (meta["height"] / meta["width"]) * char_aspect)))',
    '    return columns, rows, fps',
    '',
    'def render_frame(raw_bytes, columns, rows):',
    '    lines = []',
    '    cursor = 0',
    '    for _ in range(rows):',
    '        characters = []',
    '        for _ in range(columns):',
    '            red = raw_bytes[cursor]',
    '            green = raw_bytes[cursor + 1]',
    '            blue = raw_bytes[cursor + 2]',
    '            cursor += 3',
    '            mapped_red, mapped_green, mapped_blue, luminance = remap_pixel(red, green, blue)',
    '            char = pick_char(luminance)',
    '            if char == " ":',
    '                characters.append(" ")',
    '            else:',
    '                characters.append(f"\\x1b[38;2;{mapped_red};{mapped_green};{mapped_blue}m{char}")',
    '        lines.append("".join(characters) + "\\x1b[0m")',
    '    return "\\n".join(lines)',
    '',
    'def stream_frames(path, columns, rows, fps):',
    '    filter_graph = f"fps={fps:.4f},scale={columns}:{rows}:flags=fast_bilinear"',
    '    command = [',
    '        "ffmpeg",',
    '        "-loglevel", "error",',
    '        "-nostdin",',
    '    ]',
    '    if parse_bool(os.environ.get("ASCII_VIDEO_LOOP"), True):',
    '        command.extend(["-stream_loop", "-1"])',
    '    command.extend([',
    '        "-i", path,',
    '        "-an",',
    '        "-sn",',
    '        "-vf", filter_graph,',
    '        "-f", "rawvideo",',
    '        "-pix_fmt", "rgb24",',
    '        "-",',
    '    ])',
    '    return subprocess.Popen(command, stdout=subprocess.PIPE)',
    '',
    'def start_audio(path):',
    '    if parse_bool(os.environ.get("ASCII_VIDEO_MUTED"), False):',
    '        return None',
    '    require_binary("ffplay")',
    '    command = [',
    '        "ffplay",',
    '        "-nodisp",',
    '        "-loglevel", "error",',
    '        "-autoexit",',
    '    ]',
    '    if parse_bool(os.environ.get("ASCII_VIDEO_LOOP"), True):',
    '        command.extend(["-loop", "0"])',
    '    command.append(path)',
    '    return subprocess.Popen(command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)',
    '',
    'def main():',
    '    audio_process = None',
    '    try:',
    '        require_binary("ffmpeg")',
    '        require_binary("ffprobe")',
    '        video_path = os.environ.get("ASCII_VIDEO_PATH", "").strip()',
    '        if not video_path:',
    '            raise RuntimeError("Set ASCII_VIDEO_PATH to a local video file path before running the script.")',
    '        if not os.path.exists(video_path):',
    '            raise RuntimeError(f"Could not find the video file: {video_path}")',
    '        metadata = probe_video(video_path)',
    '        columns, rows, fps = resolve_geometry(metadata)',
    '        should_loop = parse_bool(os.environ.get("ASCII_VIDEO_LOOP"), True)',
    '        frame_size = columns * rows * 3',
    '        audio_process = start_audio(video_path)',
    '        time.sleep(0.08)',
    '        process = stream_frames(video_path, columns, rows, fps)',
    '        if process.stdout is None:',
    '            raise RuntimeError("ffmpeg did not expose a frame stream.")',
    '        sys.stdout.write("\\x1b[2J\\x1b[H\\x1b[?25l")',
    '        sys.stdout.flush()',
    '        next_frame_time = time.perf_counter()',
    '        while True:',
    '            frame = process.stdout.read(frame_size)',
    '            if len(frame) < frame_size:',
    '                break',
    '            sys.stdout.write("\\x1b[H")',
    '            sys.stdout.write(render_frame(frame, columns, rows))',
    '            sys.stdout.write("\\x1b[0m")',
    '            sys.stdout.flush()',
    '            next_frame_time += 1.0 / fps',
    '            delay = next_frame_time - time.perf_counter()',
    '            if delay > 0:',
    '                time.sleep(delay)',
    '            else:',
    '                next_frame_time = time.perf_counter()',
    '        if not should_loop and audio_process is not None:',
    '            try:',
    '                audio_process.wait(timeout=1.5)',
    '            except subprocess.TimeoutExpired:',
    '                pass',
    '    except KeyboardInterrupt:',
    '        pass',
    '    except Exception as error:',
    '        print(f"error: {error}", file=sys.stderr)',
        '        return 1',
    '    finally:',
    '        if audio_process is not None and audio_process.poll() is None:',
    '            audio_process.terminate()',
    '            try:',
    '                audio_process.wait(timeout=1)',
    '            except subprocess.TimeoutExpired:',
    '                audio_process.kill()',
    '        sys.stdout.write("\\x1b[0m\\x1b[?25h\\n")',
    '        sys.stdout.flush()',
    '    return 0',
    '',
    'if __name__ == "__main__":',
    '    raise SystemExit(main())',
  ].join('\n');
}

export function buildTerminalAsciiShellScript(settings: VideoAsciiSettings): string {
  const pythonProgram = buildTerminalAsciiPythonProgram(settings);

  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    'VIDEO_PATH=""',
    'COLUMNS_OVERRIDE=""',
    'FPS_OVERRIDE=""',
    'MUTE=0',
    'LOOP=1',
    '',
    'while [[ $# -gt 0 ]]; do',
    '  case "$1" in',
    '    -m|--mute)',
    '      MUTE=1',
    '      shift',
    '      ;;',
    '    --once)',
    '      LOOP=0',
    '      shift',
    '      ;;',
    '    -c|--columns)',
    '      COLUMNS_OVERRIDE="${2:-}"',
    '      shift 2',
    '      ;;',
    '    -f|--fps)',
    '      FPS_OVERRIDE="${2:-}"',
    '      shift 2',
    '      ;;',
    '    -h|--help)',
    '      echo "Usage: ./color-video-ascii.sh /path/to/video.mp4 [--mute] [--once] [--columns 120] [--fps 24]"',
    '      exit 0',
    '      ;;',
    '    --)',
    '      shift',
    '      break',
    '      ;;',
    '    -*)',
    '      echo "Unknown option: $1" >&2',
    '      exit 1',
    '      ;;',
    '    *)',
    '      if [[ -z "$VIDEO_PATH" ]]; then',
    '        VIDEO_PATH="$1"',
    '      else',
    '        echo "Only one video path can be supplied." >&2',
    '        exit 1',
    '      fi',
    '      shift',
    '      ;;',
    '  esac',
    'done',
    '',
    'if [[ -z "$VIDEO_PATH" ]]; then',
    '  echo "Usage: ./color-video-ascii.sh /path/to/video.mp4 [--mute] [--once] [--columns 120] [--fps 24]" >&2',
    '  exit 1',
    'fi',
    '',
    'if ! command -v ffmpeg >/dev/null 2>&1; then',
    '  echo "ffmpeg is required." >&2',
    '  exit 1',
    'fi',
    '',
    'if ! command -v ffprobe >/dev/null 2>&1; then',
    '  echo "ffprobe is required." >&2',
    '  exit 1',
    'fi',
    '',
    'if [[ "$MUTE" != "1" ]] && ! command -v ffplay >/dev/null 2>&1; then',
    '  echo "ffplay is required unless you run with --mute." >&2',
    '  exit 1',
    'fi',
    '',
    'if command -v python3 >/dev/null 2>&1; then',
    '  PYTHON_BIN="python3"',
    'elif command -v python >/dev/null 2>&1; then',
    '  PYTHON_BIN="python"',
    'else',
    '  echo "Python 3 is required." >&2',
    '  exit 1',
    'fi',
    '',
    'export ASCII_VIDEO_PATH="$VIDEO_PATH"',
    'export ASCII_VIDEO_COLS="$COLUMNS_OVERRIDE"',
    'export ASCII_VIDEO_FPS="$FPS_OVERRIDE"',
    'export ASCII_VIDEO_LOOP="$LOOP"',
    'export ASCII_VIDEO_MUTED="$MUTE"',
    '',
    '"$PYTHON_BIN" - <<\'PY\'',
    pythonProgram,
    'PY',
  ].join('\n');
}

export function buildTerminalAsciiPowerShellScript(settings: VideoAsciiSettings): string {
  const pythonProgram = buildTerminalAsciiPythonProgram(settings);

  return [
    'param(',
    '  [Parameter(Position = 0)]',
    '  [string]$Path = "",',
    '  [int]$Columns = 0,',
    '  [double]$FramesPerSecond = 0,',
    '  [switch]$Mute,',
    '  [switch]$NoLoop',
    ')',
    '',
    'function Resolve-AsciiVideoPath {',
    '  param([string]$RequestedPath)',
    '',
    '  if (-not [string]::IsNullOrWhiteSpace($RequestedPath)) {',
    '    return $RequestedPath',
    '  }',
    '',
    '  try {',
    '    Add-Type -AssemblyName System.Windows.Forms | Out-Null',
    '    $dialog = New-Object System.Windows.Forms.OpenFileDialog',
    '    $dialog.Filter = "Video files|*.mp4;*.webm;*.ogg;*.mov;*.mkv;*.avi|All files|*.*"',
    '    $dialog.Title = "Choose a video for color ASCII playback"',
    '    if ($dialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {',
    '      return $dialog.FileName',
    '    }',
    '  } catch {',
    '    # Ignore picker failures and fall back to a text prompt.',
    '  }',
    '',
    '  $typedPath = Read-Host "Enter the path to a local video file"',
    '  if (-not [string]::IsNullOrWhiteSpace($typedPath)) {',
    '    return $typedPath',
    '  }',
    '',
    '  Write-Host "Usage: .\\color-video-ascii.ps1 -Path C:\\path\\to\\video.mp4 [-Columns 120] [-FramesPerSecond 24]" -ForegroundColor Yellow',
    '  exit 1',
    '}',
    '',
    '$Path = Resolve-AsciiVideoPath -RequestedPath $Path',
    '',
    'try {',
    '  $Path = (Resolve-Path -LiteralPath $Path -ErrorAction Stop).ProviderPath',
    '} catch {',
    '  throw "Could not find the video file: $Path"',
    '}',
    '',
    'if ($null -eq (Get-Command ffmpeg -ErrorAction SilentlyContinue)) {',
    '  throw "ffmpeg is required."',
    '}',
    '',
    'if ($null -eq (Get-Command ffprobe -ErrorAction SilentlyContinue)) {',
    '  throw "ffprobe is required."',
    '}',
    '',
    'if (-not $Mute -and $null -eq (Get-Command ffplay -ErrorAction SilentlyContinue)) {',
    '  throw "ffplay is required unless you run with -Mute."',
    '}',
    '',
    'if (Get-Command py -ErrorAction SilentlyContinue) {',
    '  $pythonCommand = "py"',
    '  $pythonArgs = @("-3", "-")',
    '} elseif (Get-Command python -ErrorAction SilentlyContinue) {',
    '  $pythonCommand = "python"',
    '  $pythonArgs = @("-")',
    '} else {',
    '  throw "Python 3 is required."',
    '}',
    '',
    '$env:ASCII_VIDEO_PATH = $Path',
    'if ($Columns -gt 0) {',
    '  $env:ASCII_VIDEO_COLS = [string]$Columns',
    '} else {',
    '  Remove-Item Env:ASCII_VIDEO_COLS -ErrorAction SilentlyContinue',
    '}',
    '',
    'if ($FramesPerSecond -gt 0) {',
    '  $env:ASCII_VIDEO_FPS = [string]$FramesPerSecond',
    '} else {',
    '  Remove-Item Env:ASCII_VIDEO_FPS -ErrorAction SilentlyContinue',
    '}',
    '',
    '$env:ASCII_VIDEO_LOOP = if ($NoLoop) { "0" } else { "1" }',
    '$env:ASCII_VIDEO_MUTED = if ($Mute) { "1" } else { "0" }',
    '',
    "@'",
    pythonProgram,
    "'@ | & $pythonCommand @pythonArgs",
  ].join('\n');
}
